Repository Davis24/Breast-Cancer-Classification---SE489, pull requests merged in 2025-05, with the labels that each got.

#1 Research-knn classification
  README.md
  notebooks/exploratory/0.1-Davis-KNN.ipynb
Labels: enhancement

#3 SVM Model with data processing, training, testing
  notebooks/Model_SE489.ipynb
Labels: enhancement

#6 added phase2 template
  PHASE2.md
  README.md
  data/breast-cancer.csv
Labels: documentation

#8 Hydra
  breast_cancer_classification/conf/config.yaml
  breast_cancer_classification/conf/model/logistic_regression.yaml
  breast_cancer_classification/modeling/train.py
Labels: enhancement

#10 Logging
  breast_cancer_classification/dataset.py
  breast_cancer_classification/modeling/predict.py
  breast_cancer_classification/modeling/train.py
Labels: enhancement

#11 Fixed issues with coloring and rprint
  breast_cancer_classification/dataset.py
  breast_cancer_classification/modeling/train.py
Labels: bug

#9 Docker creation
  PHASE2.md
  docker/README.md
  docker/predict.dockerfile
  docker/train.dockerfile
  models/model.pkl
  notebooks/exploratory/0.1-Davis-KNN.ipynb
  pyproject.toml
  requirements.txt
Labels: enhancement

#12 Hydra Documentation
  PHASE2.md
  breast_cancer_classification/dataset.py
  breast_cancer_classification/modeling/predict.py
  breast_cancer_classification/modeling/train.py
Labels: documentation
